In [1]:
import numpy as np
import pandas as pd

In [2]:
CAMINHO = "C:\\Users\\Nitro\\Desktop\\Redes-Neurais\\compras.csv"

In [3]:
df = pd.read_csv(CAMINHO, header=None)
df.replace(np.nan, 0, inplace=True) # inplace = True substitui no próprio dataframe
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,citrus fruit,semi-finished bread,margarine,ready soups,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,tropical fruit,yogurt,coffee,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,whole milk,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,pip fruit,yogurt,cream cheese,meat spreads,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,other vegetables,whole milk,condensed milk,long life bakery product,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,whole milk,butter,yogurt,rice,abrasive cleaner,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,rolls/buns,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,other vegetables,UHT-milk,rolls/buns,bottled beer,liquor (appetizer),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,potted plants,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,whole milk,cereals,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
def removeAllZerosFromList(l):
    return list(filter(lambda x: x != 0, l))

In [5]:
list_all_transactions = []

for index, row in df.iterrows():
    listOfTransaction = row.values.tolist()
    listOfTransaction = removeAllZerosFromList(listOfTransaction)

    list_all_transactions.append(listOfTransaction)

print(len(list_all_transactions))
print(list_all_transactions[0])

9835
['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups']

In [9]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(list_all_transactions).transform(list_all_transactions)
df = pd.DataFrame(te_ary, columns=te.columns_) # Adiciona o título da coluna

df.head(10)

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [13]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True) # Ocorrência dos produtos

frequent_itemsets.sort_values(by=["support"], ascending=False)

      support                                     itemsets
86   0.255516                      frozenset({whole milk})
55   0.193493                frozenset({other vegetables})
66   0.183935                      frozenset({rolls/buns})
75   0.174377                            frozenset({soda})
87   0.139502                          frozenset({yogurt})
..        ...                                          ...
160  0.010066                frozenset({curd, rolls/buns})
236  0.010066       frozenset({waffles, other vegetables})
212  0.010066         frozenset({tropical fruit, napkins})
199  0.010066         frozenset({whole milk, hard cheese})
190  0.010066  frozenset({sausage, fruit/vegetable juice})

[333 rows x 2 columns]

In [19]:
from mlxtend.frequent_patterns import association_rules
# Lift é a melhor métrica
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold = 0.5)

rules.sort_values(by=["lift"], ascending=False).drop(["antecedent support", "consequent support", "leverage", "conviction"], axis = 1)

,antecedents,consequents,support,confidence,lift,representativity,zhangs_metric,jaccard,certainty,kulczynski
1,"frozenset({citrus fruit, root vegetables})",frozenset({other vegetables}),0.010371,0.586207,3.029608,1.0,0.681990,0.051646,0.486932,0.319903
6,"frozenset({tropical fruit, root vegetables})",frozenset({other vegetables}),0.012303,0.584541,3.020999,1.0,0.683367,0.060835,0.484867,0.324062
5,"frozenset({rolls/buns, root vegetables})",frozenset({other vegetables}),0.012201,0.502092,2.594890,1.0,0.629935,0.059347,0.382637,0.282575
7,"frozenset({yogurt, root vegetables})",frozenset({other vegetables}),0.012913,0.500000,2.584078,1.0,0.629266,0.062562,0.380043,0.283368
2,"frozenset({curd, yogurt})",frozenset({whole milk}),0.010066,0.582353,2.279125,1.0,0.571107,0.038313,0.439011,0.310874
0,"frozenset({butter, other vegetables})",frozenset({whole milk}),0.011490,0.573604,2.244885,1.0,0.565878,0.043512,0.427260,0.309285
11,"frozenset({tropical fruit, root vegetables})",frozenset({whole milk}),0.011998,0.570048,2.230969,1.0,0.563627,0.045350,0.422484,0.308502
12,"frozenset({yogurt, root vegetables})",frozenset({whole milk}),0.014540,0.562992,2.203354,1.0,0.560625,0.054497,0.413006,0.309948
3,"frozenset({domestic eggs, other vegetables})",frozenset({whole milk}),0.012303,0.552511,2.162336,1.0,0.549779,0.046342,0.398928,0.300331
14,"frozenset({whipped/sour cream, yogurt})",frozenset({whole milk}),0.010880,0.524510,2.052747,1.0,0.523711,0.040996,0.361316,0.283544
10,"frozenset({rolls/buns, root vegetables})",frozenset({whole milk}),0.012710,0.523013,2.046888,1.0,0.524192,0.047583,0.359305,0.286377
4,"frozenset({pip fruit, other vegetables})",frozenset({whole milk}),0.013523,0.517510,2.025351,1.0,0.519843,0.050436,0.351913,0.285217
13,"frozenset({tropical fruit, yogurt})",frozenset({whole milk}),0.015150,0.517361,2.024770,1.0,0.521384,0.056184,0.351714,0.288326
9,"frozenset({yogurt, other vegetables})",frozenset({whole milk}),0.022267,0.512881,2.007235,1.0,0.524577,0.080485,0.345695,0.300014
8,"frozenset({whipped/sour cream, other vegetables})",frozenset({whole milk}),0.014642,0.507042,1.984385,1.0,0.510816,0.054278,0.337853,0.282172